current_path = pwd;
addpath(genpath(current_path + "/.."));

g = @(x) exp(x.^2 + 2*x-2)/sin(x);
syms x;
latex_g = ['$$ g(x) = ' latex(g(x)) '$$'];

lines = {
    'Some random text not too long to fit in the image',...
    latex_g,...
    latex_g,...
    '$$(a+b)^{2} = a^{2} + ab + b^{2}$$',...
    '$$(a+b)^{2} = a^{2} + ab + b^{2}$$',...
    '$$(a+b)^{2} = a^{2} + ab + b^{2}$$',...
    '$$(a+b)^{2} = a^{2} + ab + b^{2}$$',...
    'Last line of random text'
};

LatexPlot.show(lines);
